### ISSUE TITLE
Build error for `img/nested_config.pdf`

### ISSUE THREAD

**Issue by jschlatow** [nfeske/genode-manual#10]
When building the foundations, I get a `TeX capacity exceeded, sorry [grouping levels=255]` error that is caused by `img/nested_config.tikz`. The same error occurs when I try to build `img/nested_config.pdf`. Here is an excerpt from the log:

```
(./tikz-common.tex)) (./nested_config.tikz
! TeX capacity exceeded, sorry [grouping levels=255].
\pgfpicture ->\begingroup 
                          \pgfpicturetrue \global \advance \pgf@picture@seri...
l.66 }
```

**Comment by nfeske** [comment]
Unfortunately, I have not the slightest idea what this is about.

**Comment by jschlatow** [comment]
That means you cannot reproduce this? Which texlive version are you using?

**Comment by jschlatow** [comment]
Using `lualatex` instead of `pdflatex` appears to be a solution.

**Comment by nfeske** [comment]
The version I use is pretty old:

```
$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian)
```

It's great that you found a solution.

**Comment by jschlatow** [comment]
I tried pdflatex from texlive 2017, 2019, 2021 and 2022. Only texlive 2017 was able to compile it successfully.
