### ISSUE TITLE
Build failed due to missing chapter tag

### ISSUE THREAD

**Issue by zeehha** [nfeske/genode-manual#6]
Hi,

I get the following error when building Genode foundations 20.05:

`gosh --style manual.gosh genode-foundations-20-05.txt > misc.tmp.tex
can't read "chapter_tag": no such variable` 

entire log: [build-log.txt](https://github.com/nfeske/genode-manual/files/5151443/build-log.txt)

I made sure that I have all required programs.

Best,
Chris

**Comment by nfeske** [comment]
Unfortunately, I am unable to reproduce this issue. The error message gives me no obvious hint either.

May it be related to the Tcl version installed? For reference, I'm using tclsh8.6.

**Comment by zeehha** [comment]
I upgraded tclsh from 8.6.0 to 8.6.9, however I still get the error.

**Comment by nfeske** [comment]
I'm closing this issue since I'm unable to reproduce it and it has become stale.
